import React from 'react';
import {
    Modal
} from 'semantic-ui-react'

export default class PolicyDialog extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            open: false
        };
    }
    render() {
        return (
            <Modal
                open={this.state.open}
                onClose={() => this.setState({ open: false })}
                onOpen={() => this.setState({ open: true })}
                // eslint-disable-next-line
                trigger={<a href="#">privacy policy.</a>}
            >
                <Modal.Header>Privacy Policy</Modal.Header>
                <Modal.Content scrolling>
                    <Modal.Description>
                        <p>
                            We are committed to ensuring that your privacy is protected and we shall endeavour to
                            use any information that you provide when using this website in accordance with this privacy policy. We may amend this policy from time to time by updating this page. Therefore, we
                            suggest you check this page occasionally to ensure you are aware of and are happy with any amendments.
                        </p>
                        <p><b>Google Analytics</b></p>
                        <div>
                            <p>
                                To collect information about how visitors use our website and to improve our services, we are
                                using
                                Google Analytics on this website. You can find out more about how Google Analytics works and about
                                how information is collected on the Google Analytics terms of services and on Google’s privacy policy.
                            </p>

                            <ul>
                                <li>Google Analytics Terms of Service: <a href="http://www.google.com/analytics/terms/us.html"
                                    onClick="gtag('event', 'out', {'event_category': 'privacy.html','event_label':'ga-terms'});">http://www.google.com/analytics/terms/us.html</a>
                                </li>
                                <li>Google Privacy Policy: <a href="https://policies.google.com/privacy?hl=en"
                                    onClick="gtag('event', 'out', {'event_category': 'privacy.html','event_label':'google-privacy'});">https://policies.google.com/privacy?hl=en</a>
                                </li>
                                <li>Google Analytics Opt-out Add-on: <a href="https://tools.google.com/dlpage/gaoptout?hl=en"
                                    onClick="gtag('event', 'out', {'event_category': 'privacy.html','event_label':'ga-opt-out'});">https://tools.google.com/dlpage/gaoptout?hl=en</a>
                                </li>
                            </ul>
                        </div>
                        <p>
                            Our website uses Google Analytics, a web analytics service provided by Google, Inc.
                            ("Google"). The information generated by the cookie about your use of our website (including your IP
                            address) will be transmitted to and stored by Google on servers in the United States. Google will use this
                            information for the purpose of evaluating your use of our website, compiling reports on website activity for
                            website operators and providing other services relating to website activity and internet usage. Google may
                            also transfer this information to third parties where required to do so by law, or where such third parties
                            process the information on Google’s behalf.
                            <p><b>Changes</b></p>
                                <p>
                                    We may make changes to this privacy policy from time to time. If we change our
                                    privacy policy we will post the changes on this page. Continued use of the service will signify that
                                    you agree to any such changes.
                                </p>
                                <p><b>Your acceptance of this privacy policy</b></p>
                                <p>If you do not agree to this privacy policy, please do not use our site.</p>
                                <p>
                                    By using our site, you consent to the collection and use of information by us. Owing
                                    to the global nature of the internet infrastructure, the information you provide may be transferred in
                                    transit to countries outside the European Economic Area that do not have similar protections in place
                                    regarding your data and its use as set out in this policy. However, we have taken the steps outlined above
                                    to try to improve the security of your information. By submitting your information you consent to these
                                    transfers.
                                </p>
                                To find out more about your rights under the Data Protection Act, visit the
                                Information Commissioner’s website:
                            <a href="www.dataprotection.gov.uk">www.dataprotection.gov.uk</a> or read the Act online at:
                            <a href="http://www.hmso.gov.uk/acts/acts1998/19980029.htm">www.hmso.gov.uk/acts/acts1998/19980029.htm</a>.
                        </p>

                    </Modal.Description>
                </Modal.Content>
            </Modal>
        )
    }
}
